### ISSUE TITLE
Globalwarming throws an error on load

### ISSUE THREAD

**Issue by mpdk** [nsporillo/GlobalWarming#29]
[07:57:25] [Server thread/INFO]: [GlobalWarming] Enabling GlobalWarming v1.0.1
[07:57:25] [Server thread/INFO]: [GlobalWarming] Lang loaded: [en-US]
[07:57:29] [Server thread/ERROR]: [GlobalWarming] MySQL connection not found.
[07:57:29] [Server thread/ERROR]: [GlobalWarming] Data won't persist after restarts!
[07:57:29] [Server thread/ERROR]: [GlobalWarming] Please update config.yml and restart the server.
[07:57:29] [Server thread/ERROR]: Error occurred while enabling GlobalWarming v1.0.1 (Is it up to date?)
java.lang.NullPointerException: null
        at net.porillo.config.WorldConfig.loadKeys(WorldConfig.java:54) ~[?:?]
        at net.porillo.config.ConfigLoader.load(ConfigLoader.java:52) ~[?:?]
        at net.porillo.config.WorldConfig.<init>(WorldConfig.java:30) ~[?:?]
        at net.porillo.engine.ClimateEngine.loadWorldClimateEngines(ClimateEngine.java:37) ~[?:?]
        at net.porillo.GlobalWarming.onEnable(GlobalWarming.java:87) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by nsporillo** [comment]
Hi, this has to do with a faulty assumption we make with our world configurations. We allow for carbon emissions that happen in the nether and the end to be associated with the carbon scores in the main world, but the default value can cause this null pointer exception.
